name: CI

on: [push, pull_request]

jobs:
  test-windows:
    name: >-
      ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2022, windows-2019 ]
        ruby: [ mswin, mingw, head, "3.0", "2.7", "2.6" ]
    steps:
      - name: repo checkout
        uses: actions/checkout@v2

      - name: load ruby, install/update gcc, install openssl
        uses: MSP-Greg/setup-ruby-pkgs@win-ucrt-2
        with:
          ruby-version: ${{ matrix.ruby }}
          mingw: _upgrade_ openssl
          setup-ruby-ref: MSP-Greg/ruby-setup-ruby/win-ucrt-1

      - name: depends
        run:  bundle install

      # pkg-config is disabled because it can pick up the different OpenSSL installation
      # SSL_DIR is set as needed by MSP-Greg/setup-ruby-pkgs
      # only used with mswin
      - name: compile
        run:  rake compile -- --enable-debug --without-pkg-config $env:SSL_DIR

      - name: test
        run:  rake test TESTOPTS="-v --no-show-detail-immediately" OSSL_MDEBUG=1
