name: CI

on: [push, pull_request]

jobs:
  test:
    name: >-
      ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        ruby: [ head, "3.1", "3.0", "2.7", "2.6" ]
        include:
          - { os: ubuntu-22.04, ruby: head }
          - { os: ubuntu-22.04, ruby: "3.1" }
          - { os: windows-latest, ruby: ucrt }
          - { os: windows-latest, ruby: mswin }
        exclude:
          - { os: windows-latest, ruby: head }

    steps:
      - name: repo checkout
        uses: actions/checkout@v3

      - name: load ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: depends
        run:  bundle install

      - name: compile
        run:  rake compile -- --enable-debug

      - name: test
        run:  rake test TESTOPTS="-v --no-show-detail-immediately" OSSL_MDEBUG=1
